/**
 * Dacia Campaign III release state (KAN-357 to KAN-361).
 *
 * These records are generated by scripts/dacia/build.py. Keeping the release
 * decision in the generated data means a component cannot make a blocked seam
 * or an uninspected object public by changing presentation code.
 */
import borroczyn from '../data/dacia/generated/borroczyn.json';
import inManibus from '../data/dacia/generated/in-manibus.json';

export type BorroczynLayerRole = 'historical_source' | 'georeferenced_derived' | 'modern_reference';

export interface BorroczynLayer {
  id: string;
  role: BorroczynLayerRole;
  sourceId: string;
  status: string;
  title: string;
  rightsStatus: string;
  productionRole: string;
}

export function getBorroczynPackage() {
  return borroczyn;
}

export function getBorroczynLayers(): BorroczynLayer[] {
  return [...(borroczyn.layers as BorroczynLayer[])];
}

export function getInManibusPackage() {
  return inManibus;
}

export function campaignIIIReleaseReady(): boolean {
  return borroczyn.publicReady && inManibus.publicReady;
}

export function campaignIIIHolds(): string[] {
  const holds = [...borroczyn.blockers];
  if (inManibus.holdReason) holds.push(inManibus.holdReason);
  return holds;
}
