/**
 * Cross-essay corpus (ATLAS-501) + rich catalogue backbone (ATLAS-801 / KAN-65)
 *
 * A unified list of individual historical maps referenced across the essays,
 * each geolocated (where it depicts / was made) so the atlas can plot the whole
 * corpus on one map + timeline. Coordinates are [lng, lat] (GeoJSON order).
 *
 * This is authored data, not derived - it links a map to its source essay so
 * pins deep-link back into the essay that discusses it.
 *
 * The record schema is a *superset*: every field the collection catalogue will
 * eventually surface (cartographer, provenance, bibliography, imagery…) is
 * present but optional/defaulted, so today's 15 seed records validate unchanged.
 * The atlas map only ever consumes the `MapCore` projection (see getCorpusCore),
 * which keeps the heavyweight catalogue metadata out of the inline client
 * payload it ships to every visitor.
 */
import { z } from 'astro:content';
import { ROOM_SLUGS } from '../data/rooms';

/**
 * An inline citation on a map - a self-contained reference that isn't (yet) in
 * the shared bibliography registry. Records may instead cite a registry entry
 * by its string key; see `MapBibRefSchema` (KAN-70).
 */
export const InlineBibSchema = z.object({
  citation: z.string(),
  url: z.string().optional(),
  author: z.string().optional(),
  year: z.number().optional(),
  title: z.string().optional(),
});

/** A map cites a work either by shared-registry key (string) or inline. */
export const MapBibRefSchema = z.union([z.string(), InlineBibSchema]);
export type MapBibRef = z.infer<typeof MapBibRefSchema>;

/**
 * A reproduction / scan of the map, with attribution + licensing. When a
 * high-resolution tiled source is available (KAN-69), `dziTileSource` (a DeepZoom
 * .dzi produced by scripts/build-map-tiles.mjs) or `iiif` (an IIIF info.json)
 * opts the image into the pan/zoom viewer; `src` stays the static fallback.
 */
export const MapImageSchema = z.object({
  src: z.string(),
  alt: z.string(),
  credit: z.string().optional(),
  license: z.string().optional(),
  dziTileSource: z.string().optional(),
  iiif: z.string().optional(),
});

/**
 * The full catalogue record. `MapCoreSchema` below picks the atlas-critical
 * subset; everything outside that subset is optional and defaults to empty so
 * the existing seed data (core fields only) parses without modification.
 */
export const HistoricalMapSchema = z.object({
  // --- Atlas-critical core (mirrored by MapCoreSchema) ---
  id: z.string(),
  title: z.string(),
  year: z.number(), // negative = BC
  essaySlug: z.string(),
  region: z.string(),
  coords: z.tuple([z.number(), z.number()]), // [lng, lat]
  blurb: z.string().optional(),

  // --- Rich catalogue metadata (all optional / defaulted) ---
  cartographer: z.string().optional(), // free-text maker (display fallback)
  cartographerId: z.string().optional(), // link into the cartographer registry
  publisher: z.string().optional(),
  engraver: z.string().optional(),
  edition: z.string().optional(),
  state: z.string().optional(),
  dimensions: z.string().optional(), // e.g. "54 × 41 cm"
  scale: z.string().optional(),
  medium: z.string().optional(), // e.g. "copper engraving, hand-coloured"
  condition: z.string().optional(),
  provenance: z.string().optional(),
  acquisition: z.string().optional(),
  objectType: z.string().optional(),
  repository: z.string().optional(),
  repositoryId: z.string().optional(),
  sourceUrl: z.string().url().optional(),
  rightsStatement: z.string().optional(),
  attribution: z.string().optional(),
  publicationStatus: z.enum(['published_witness', 'reference_only']).optional(),
  bibliography: z.array(MapBibRefSchema).default([]),
  relatedMapIds: z.array(z.string()).default([]),
  relatedEssaySlugs: z.array(z.string()).default([]),
  images: z.array(MapImageSchema).default([]),
  tags: z.array(z.string()).default([]),
  coveragePath: z.string().optional(), // depicted extent; fragment into the merged coverage.geojson (KAN-74)
  // Seven-room cosmography (TC-102 / KAN-93). Optional here so existing seed
  // records validate unchanged; retro-tagging lands in KAN-94.
  room: z.enum(ROOM_SLUGS).optional(),
  secondaryRooms: z.array(z.enum(ROOM_SLUGS)).max(2).default([]),
  roomAnchor: z.boolean().default(false),
});

export type HistoricalMap = z.infer<typeof HistoricalMapSchema>;

/**
 * The atlas-critical subset - exactly the fields the MapLibre island needs to
 * plot a pin, filter it, and deep-link back to its essay. AtlasMap serialises
 * *this* shape into its inline payload so rich catalogue fields never inflate
 * the bytes every visitor downloads.
 */
export const MapCoreSchema = HistoricalMapSchema.pick({
  id: true,
  title: true,
  year: true,
  essaySlug: true,
  region: true,
  coords: true,
  blurb: true,
});

export type MapCore = z.infer<typeof MapCoreSchema>;

const RAW: unknown[] = [
  // The Cartographic Sacrifice
  {
    id: 'babylonian',
    room: 'map',
    secondaryRooms: ['theatre'],
    coveragePath: '/geo/coverage.geojson#babylonian',
    title: 'Babylonian World Map',
    year: -600,
    essaySlug: 'cartography',
    region: 'Mesopotamia',
    coords: [44.42, 32.54],
    blurb: 'The Imago Mundi - earth as a disc ringed by the bitter river.',
    bibliography: ['harley-2001', 'brotton-2012'],
  },
  {
    id: 'eratosthenes',
    room: 'map',
    coveragePath: '/geo/coverage.geojson#eratosthenes',
    title: "Eratosthenes' World",
    year: -220,
    essaySlug: 'cartography',
    region: 'Alexandria',
    coords: [29.92, 31.2],
    blurb: 'A measured earth: the first grid of parallels and meridians.',
  },
  {
    id: 'hereford',
    room: 'theatre',
    secondaryRooms: ['map', 'city'],
    roomAnchor: true,
    coveragePath: '/geo/coverage.geojson#hereford',
    title: 'Hereford Mappa Mundi',
    year: 1300,
    essaySlug: 'invisible-maps-religion',
    region: 'Hereford',
    coords: [-2.72, 52.06],
    blurb:
      'An east-up, encyclopedic Christian world gathered around Jerusalem on a single monumental skin.',
    cartographer: 'Richard of Haldingham (traditional attribution)',
    dimensions: 'Approximately 158 × 133 cm; geographic circle 132 cm in diameter',
    medium: 'Ink and pigments on a single sheet of vellum',
    provenance: 'Hereford Cathedral',
    bibliography: ['woodward-1987-mappaemundi', 'edson-1997', 'hereford-cathedral'],
    relatedMapIds: ['religion-ebstorf', 'religion-psalter', 'religion-matthew-paris'],
    relatedEssaySlugs: ['cartography'],
    images: [
      {
        src: '/images/invisible-maps-religion/hereford.jpg',
        alt: 'Hereford Mappa Mundi, an east-up world map centred on Jerusalem',
        credit: 'Public-domain reproduction via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['mappamundi', 'Jerusalem', 'east-up', 'sacred centre', 'manuscript'],
  },
  {
    id: 'religion-madaba',
    room: 'city',
    secondaryRooms: ['theatre', 'road'],
    title: 'Madaba mosaic map, Jerusalem detail',
    year: 570,
    essaySlug: 'invisible-maps-religion',
    region: 'Madaba and the Holy Land',
    coords: [35.79, 31.72],
    blurb:
      'A sixth-century church-floor mosaic enlarges Jerusalem into a legible sacred city and destination.',
    cartographer: 'Unknown Byzantine mosaicists',
    medium: 'Floor mosaic',
    provenance: 'Church of Saint George, Madaba',
    bibliography: ['woodward-1987-mappaemundi', 'edson-1997'],
    relatedMapIds: ['hereford', 'religion-matthew-paris'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Madaba%20map.jpg?width=1600',
        alt: 'Surviving portion of the Madaba mosaic map with Jerusalem represented in detail',
        credit: 'Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['mosaic', 'Jerusalem', 'sacred centre', 'city', 'pilgrimage'],
  },
  {
    id: 'religion-beatus',
    room: 'theatre',
    secondaryRooms: ['map', 'archive'],
    title: 'Saint-Sever Beatus world map',
    year: 1050,
    essaySlug: 'invisible-maps-religion',
    region: 'Saint-Sever',
    coords: [-0.57, 43.76],
    blurb:
      'An east-up world in an Apocalypse commentary joins geography to apostolic and sacred history.',
    cartographer: 'Stephanus Garsia and workshop',
    medium: 'Illuminated manuscript; displayed through a later facsimile',
    bibliography: ['woodward-1987-mappaemundi', 'edson-1997'],
    relatedMapIds: ['religion-ebstorf', 'religion-psalter', 'hereford'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Facsimile%20of%20the%20Mappa%20mundi%20of%20Saint-Sever%20Beatus.jpg?width=1600',
        alt: 'Facsimile of the east-up Saint-Sever Beatus world map',
        credit: '1896 public-domain facsimile via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['Beatus', 'mappamundi', 'east-up', 'manuscript', 'sacred history'],
  },
  {
    id: 'religion-ebstorf',
    room: 'theatre',
    secondaryRooms: ['map', 'archive'],
    title: 'Ebstorf world map',
    year: 1235,
    essaySlug: 'invisible-maps-religion',
    region: 'Ebstorf',
    coords: [10.54, 53.05],
    blurb:
      'Known through photographs and facsimiles, the monumental world was figured within the body of Christ.',
    cartographer: 'Unknown',
    medium: 'Lost medieval manuscript map; facsimile witness',
    condition: 'Original destroyed in Hanover in 1943',
    bibliography: ['woodward-1987-mappaemundi', 'edson-1997'],
    relatedMapIds: ['religion-beatus', 'religion-psalter', 'hereford'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ebstorfer%20Weltkarte%202.jpg?width=1600',
        alt: 'Public-domain facsimile of the Ebstorf world map',
        credit: 'Wikimedia Commons facsimile tradition',
        license: 'Public domain',
      },
    ],
    tags: ['mappamundi', 'body of Christ', 'east-up', 'facsimile', 'lost map'],
  },
  {
    id: 'religion-psalter',
    room: 'theatre',
    secondaryRooms: ['map'],
    title: 'Psalter world map',
    year: 1250,
    essaySlug: 'invisible-maps-religion',
    region: 'England',
    coords: [-0.13, 51.51],
    blurb:
      'A compact east-up world image makes encyclopedic sacred geography available inside devotional reading.',
    cartographer: 'Unknown',
    medium: 'Ink and pigments on parchment',
    provenance: 'British Library, Additional MS 28681, fol. 9r',
    bibliography: ['woodward-1987-mappaemundi', 'edson-1997'],
    relatedMapIds: ['religion-beatus', 'religion-ebstorf', 'hereford'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Psalter%20world%20map.jpg?width=1400',
        alt: 'The compact east-up world map in the medieval Psalter manuscript',
        credit: 'British Library reproduction via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['mappamundi', 'psalter', 'east-up', 'manuscript', 'devotion'],
  },
  {
    id: 'religion-matthew-paris',
    room: 'road',
    secondaryRooms: ['theatre', 'city'],
    title: 'Itinerary from London toward Jerusalem',
    year: 1255,
    essaySlug: 'invisible-maps-religion',
    region: 'England to the Holy Land',
    coords: [-0.34, 51.75],
    blurb:
      'Matthew Paris turns pilgrimage into a vertical sequence of cities, seas and stations rather than a uniform surface.',
    cartographer: 'Matthew Paris',
    cartographerId: 'matthew-paris',
    medium: 'Ink and pigments on parchment',
    provenance: 'British Library, Royal MS 14 C VII, fol. 2',
    bibliography: ['bl-royal-14-c-vii', 'edson-1997'],
    relatedMapIds: ['religion-madaba', 'hereford'],
    images: [
      {
        src: '/images/invisible-maps-religion/matthew-paris.jpg',
        alt: 'Matthew Paris itinerary from London toward the Holy Land arranged as a vertical route',
        credit: 'British Library via Wikimedia Commons',
        license: 'CC0 / public domain',
      },
    ],
    tags: ['itinerary', 'pilgrimage', 'Jerusalem', 'route', 'manuscript'],
  },
  {
    id: 'religion-to-1472',
    room: 'theatre',
    secondaryRooms: ['archive', 'map'],
    title: 'T–O map in the first printed Etymologiae',
    year: 1472,
    essaySlug: 'invisible-maps-religion',
    region: 'Augsburg',
    coords: [10.9, 48.37],
    blurb: 'A small woodcut transmits an inherited tripartite world as a portable printed diagram.',
    cartographer: 'After Isidore of Seville',
    publisher: 'Günther Zainer',
    edition: 'Etymologiae, Augsburg, 1472',
    medium: 'Woodcut in a printed book',
    bibliography: ['woodward-1987-mappaemundi'],
    relatedMapIds: ['religion-rudimentum', 'religion-bunting'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/T%20and%20O%20map%20Guntherus%20Ziner%201472.jpg?width=1200',
        alt: 'Circular T–O world diagram printed by Günther Zainer in 1472',
        credit: 'Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['T-O map', 'woodcut', 'incunable', 'diagram', 'east-up'],
  },
  {
    id: 'religion-rudimentum',
    room: 'archive',
    secondaryRooms: ['theatre'],
    title: 'World map in the Rudimentum Novitiorum',
    year: 1475,
    essaySlug: 'invisible-maps-religion',
    region: 'Lübeck',
    coords: [10.69, 53.87],
    blurb:
      'An incunable combines universal history, genealogical apparatus and printed world maps in one book.',
    cartographer: 'Unknown; printed by Lucas Brandis',
    publisher: 'Lucas Brandis',
    edition: 'Rudimentum Novitiorum, 5 August 1475',
    medium: 'Woodcut in a printed book',
    provenance: 'Library of Congress, Lessing J. Rosenwald Collection',
    bibliography: ['loc-rudimentum', 'woodward-1987-mappaemundi'],
    relatedMapIds: ['religion-to-1472', 'religion-bunting'],
    tags: ['incunable', 'world history', 'woodcut', 'diagram', 'print'],
  },
  {
    id: 'religion-bunting',
    room: 'theatre',
    secondaryRooms: ['archive', 'city'],
    title: 'The world in a clover leaf',
    year: 1581,
    essaySlug: 'invisible-maps-religion',
    region: 'Magdeburg',
    coords: [11.63, 52.13],
    blurb:
      'Bünting arranges three continents as a Christian emblem whose leaves meet at Jerusalem.',
    cartographer: 'Heinrich Bünting',
    cartographerId: 'heinrich-bunting',
    edition: 'Itinerarium Sacrae Scripturae, 1581 edition',
    medium: 'Woodcut in a printed book',
    bibliography: ['woodward-1987-mappaemundi', 'harley-2001'],
    relatedMapIds: ['religion-to-1472', 'religion-rudimentum', 'hereford'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/1581%20Clover%20Leaf%20World%20Map%20by%20Heinrich%20Buenting.jpg?width=1600',
        alt: 'Heinrich Bünting clover-leaf world map centred on Jerusalem',
        credit: 'Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['clover leaf', 'Jerusalem', 'emblem', 'woodcut', 'print'],
  },
  {
    id: 'mercator',
    room: 'map',
    coveragePath: '/geo/coverage.geojson#mercator',
    title: 'Mercator Projection',
    year: 1569,
    essaySlug: 'cartography',
    region: 'Duisburg',
    coords: [6.76, 51.43],
    blurb: 'Rhumb lines made straight - navigation bought with area.',
    cartographer: 'Gerardus Mercator',
    cartographerId: 'mercator',
    bibliography: ['snyder-1993', 'brotton-2012'],
  },
  {
    id: 'cassini',
    room: 'map',
    coveragePath: '/geo/coverage.geojson#cassini',
    title: 'Carte de Cassini',
    year: 1744,
    essaySlug: 'cartography',
    region: 'France',
    coords: [2.35, 48.85],
    blurb: 'Triangulation turns a kingdom into a survey.',
    cartographer: 'César-François Cassini de Thury',
    cartographerId: 'cassini',
    bibliography: ['edney-2019'],
  },
  {
    id: 'blue-marble',
    room: 'map',
    secondaryRooms: ['earth'],
    coveragePath: '/geo/coverage.geojson#blue-marble',
    title: 'The Blue Marble',
    year: 1972,
    essaySlug: 'cartography',
    region: 'Global',
    coords: [0, 0],
    blurb: 'Earth seen whole, from outside - the photographic map.',
  },

  // La Rotta e il Catasto (Venice vs Sicily)
  {
    id: 'carta-pisana',
    room: 'road',
    coveragePath: '/geo/coverage.geojson#carta-pisana',
    title: 'Carta Pisana',
    year: 1290,
    essaySlug: 'venice-sicily',
    region: 'Mediterranean',
    coords: [9.5, 41],
    blurb: 'The oldest surviving portolan - the sea as a web of bearings.',
    bibliography: ['campbell-1987', 'harley-2001'],
    relatedEssaySlugs: ['invisible-maps-trade'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Carte%20Pisane%20Portolan.jpg?width=1600',
        alt: 'Carta Pisana, a portolan chart of the Mediterranean',
        credit: 'Bibliothèque nationale de France via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['portolan', 'navigation', 'trade'],
  },
  {
    id: 'fra-mauro',
    room: 'road',
    secondaryRooms: ['theatre'],
    coveragePath: '/geo/coverage.geojson#fra-mauro',
    title: 'Fra Mauro world map',
    year: 1459,
    essaySlug: 'venice-sicily',
    region: 'Venice',
    coords: [12.34, 45.44],
    blurb: "Venice's encyclopaedic world, drawn south-up.",
    cartographer: 'Fra Mauro',
    cartographerId: 'fra-mauro',
    bibliography: ['harley-2001', 'brotton-2012'],
    relatedEssaySlugs: ['invisible-maps-trade'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/FraMauroDetailedMap.jpg?width=1600',
        alt: 'Detailed south-up world map made by Fra Mauro',
        credit: 'Biblioteca Nazionale Marciana via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['world map', 'Venice', 'trade', 'cosmography'],
  },
  {
    id: 'idrisi',
    room: 'road',
    coveragePath: '/geo/coverage.geojson#idrisi',
    title: "Al-Idrisi's Tabula Rogeriana",
    year: 1154,
    essaySlug: 'venice-sicily',
    region: 'Sicily',
    coords: [13.36, 38.12],
    blurb: 'Made at the Norman court of Palermo for Roger II.',
    cartographer: 'Muhammad al-Idrisi',
    cartographerId: 'al-idrisi',
    bibliography: [
      'harley-2001',
      {
        citation:
          'S. Maqbul Ahmad, "Cartography of al-Sharīf al-Idrīsī", in The History of Cartography, vol. 2.1 (1992), 156–174.',
        author: 'Ahmad, S. Maqbul',
        year: 1992,
        title: 'Cartography of al-Sharīf al-Idrīsī',
      },
    ],
  },
  {
    id: 'trade-loc-portolan',
    room: 'road',
    secondaryRooms: ['border'],
    title: 'Portolan chart of the Mediterranean and Black Seas',
    year: 1335,
    essaySlug: 'invisible-maps-trade',
    region: 'Mediterranean and Black Seas',
    coords: [18, 37],
    blurb:
      'An anonymous vellum chart turns the Mediterranean and Black Seas into a continuous field of named coasts and bearings.',
    bibliography: ['campbell-1987', 'harley-2001'],
    relatedMapIds: ['carta-pisana'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Portolan%20chart%20of%20the%20Mediterranean%20Sea%20ca.%201320-1350%20-%20manuscript%20chart%20of%20the%20Mediterranean%20and%20Black%20seas%20on%20vellum.%20LOC%202003630429.jpg?width=1600',
        alt: 'Anonymous portolan chart of the Mediterranean and Black Seas',
        credit: 'Library of Congress, Geography and Map Division',
        license: 'Public domain',
      },
    ],
    tags: ['portolan', 'navigation', 'trade', 'Black Sea'],
  },
  {
    id: 'trade-vesconte-1311',
    room: 'road',
    secondaryRooms: ['map'],
    title: 'Eastern Mediterranean portolan',
    year: 1311,
    essaySlug: 'invisible-maps-trade',
    region: 'Eastern Mediterranean',
    coords: [23, 38],
    blurb:
      'Pietro Vesconte’s signed chart presents the eastern Mediterranean as an ordered sequence of coasts and crossings.',
    cartographer: 'Pietro Vesconte',
    cartographerId: 'pietro-vesconte',
    bibliography: ['campbell-1987'],
    relatedMapIds: ['trade-vesconte-1321'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/1311%20portolan%20of%20Pietro%20Vesconte.jpg?width=1400',
        alt: 'Pietro Vesconte portolan chart dated 1311',
        credit: 'Archivio di Stato di Firenze via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['portolan', 'navigation', 'trade', 'eastern Mediterranean'],
  },
  {
    id: 'trade-vesconte-1321',
    room: 'road',
    secondaryRooms: ['map'],
    title: 'Western Mediterranean from a portolan atlas',
    year: 1321,
    essaySlug: 'invisible-maps-trade',
    region: 'Western Mediterranean',
    coords: [7, 40],
    blurb:
      'A western Mediterranean atlas leaf extends Vesconte’s navigational grammar across a second maritime field.',
    cartographer: 'Pietro Vesconte',
    cartographerId: 'pietro-vesconte',
    bibliography: ['campbell-1987'],
    relatedMapIds: ['trade-vesconte-1311'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/West%20Mediterranean%20from%20Vesconte%20c.1321%20(Lyon)%20atlas.jpg?width=1400',
        alt: 'Western Mediterranean portolan atlas leaf by Pietro Vesconte',
        credit: 'Bibliothèque municipale de Lyon via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['portolan', 'navigation', 'trade', 'western Mediterranean'],
  },
  {
    id: 'trade-bianco-1436',
    room: 'road',
    secondaryRooms: ['map'],
    title: 'Portolan leaves from the Andrea Bianco atlas',
    year: 1436,
    essaySlug: 'invisible-maps-trade',
    region: 'Venice',
    coords: [12.34, 45.44],
    blurb:
      'Andrea Bianco’s atlas binds portolan leaves, tables and cosmographic material into one Venetian working manuscript.',
    cartographer: 'Andrea Bianco',
    cartographerId: 'andrea-bianco',
    bibliography: ['campbell-1987', 'lane-1973'],
    tags: ['atlas', 'portolan', 'Venice', 'trade'],
  },
  {
    id: 'trade-roselli-1466',
    room: 'road',
    title: 'Portolan chart of the Mediterranean',
    year: 1466,
    essaySlug: 'invisible-maps-trade',
    region: 'Mediterranean',
    coords: [2.65, 39.57],
    blurb:
      'Petrus Roselli’s chart preserves the dense coastal names and rhumb network of the Majorcan portolan tradition.',
    cartographer: 'Petrus Roselli',
    cartographerId: 'petrus-roselli',
    bibliography: ['campbell-1987'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Petrus%20Roselli%20-%20Portolan%20Chart%20of%20the%20Mediterranean%20(1466).png?width=1600',
        alt: 'Petrus Roselli portolan chart of the Mediterranean dated 1466',
        credit: 'James Ford Bell Library via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['portolan', 'Majorca', 'navigation', 'trade'],
  },
  {
    id: 'trade-agnese-1544',
    room: 'road',
    secondaryRooms: ['theatre'],
    title: 'Portolan atlas of nine charts and a world map',
    year: 1544,
    essaySlug: 'invisible-maps-trade',
    region: 'Venice',
    coords: [12.34, 45.44],
    blurb:
      'Battista Agnese’s workshop joins navigational charts and a world map in a richly illuminated Venetian atlas.',
    cartographer: 'Battista Agnese',
    cartographerId: 'battista-agnese',
    bibliography: ['campbell-1987', 'lane-1973'],
    tags: ['atlas', 'portolan', 'Venice', 'trade'],
  },
  {
    id: 'trade-barbari-1500',
    room: 'city',
    secondaryRooms: ['road'],
    title: 'View of Venice',
    year: 1500,
    essaySlug: 'invisible-maps-trade',
    region: 'Venice',
    coords: [12.34, 45.44],
    blurb:
      'Jacopo de’ Barbari turns the lagoon into an inspectable city while the wider commercial network remains beyond the frame.',
    cartographer: 'Jacopo de’ Barbari',
    cartographerId: 'jacopo-de-barbari',
    bibliography: ['lane-1934', 'lane-1973', 'mia-barbari'],
    relatedEssaySlugs: ['venice-sicily', 'cities-remember'],
    images: [
      {
        src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Jacopo_de%27_Barbari_-_View_of_Venice_-_Minneapolis_Institute_of_Art.jpg/1280px-Jacopo_de%27_Barbari_-_View_of_Venice_-_Minneapolis_Institute_of_Art.jpg',
        alt: 'Jacopo de’ Barbari bird’s-eye View of Venice',
        credit: 'Minneapolis Institute of Art',
        license: 'Public Domain Mark',
      },
    ],
    tags: ['Venice', 'city view', 'print', 'trade'],
  },
  {
    id: 'city-forma-urbis',
    room: 'archive',
    secondaryRooms: ['city', 'map'],
    title: 'Forma Urbis Romae',
    year: 210,
    essaySlug: 'cities-remember',
    region: 'Rome',
    coords: [12.4875, 41.8921],
    blurb:
      'The Severan marble plan survives in 1,186 known fragments, turning the mapped city into an evidence problem of joins, proposed locations and absences.',
    cartographer: 'Unknown Severan-period surveyors and stonecutters',
    scale: 'Approximately 1:240',
    dimensions: 'Approximately 18.1 × 13 m when mounted',
    medium: 'Incised marble slabs',
    condition: 'Fragmentary; known through 1,186 surviving pieces',
    provenance: 'Museo della Forma Urbis, Rome',
    bibliography: ['stanford-forma-urbis'],
    relatedMapIds: ['city-bufalini-1551', 'city-nolli-1748'],
    tags: ['Rome', 'fragment', 'marble plan', 'evidence state', 'architecture'],
  },
  {
    id: 'city-schedel-nuremberg',
    room: 'theatre',
    secondaryRooms: ['city', 'archive'],
    title: 'Nuremberg in the Liber Chronicarum',
    year: 1493,
    essaySlug: 'cities-remember',
    region: 'Nuremberg',
    coords: [11.0767, 49.4521],
    blurb:
      'A coloured chronicle-page view remembers Nuremberg through wall, gate, church towers and concentrated civic profile.',
    cartographer: 'Workshop of Michael Wolgemut and Wilhelm Pleydenwurff',
    publisher: 'Anton Koberger',
    edition: 'Liber Chronicarum, Nuremberg, 1493',
    medium: 'Hand-coloured woodcut in a printed book',
    provenance: 'Bavarian State Library witness; Library of Congress WDL delivery',
    bibliography: ['loc-nuremberg-chronicle'],
    relatedMapIds: ['trade-barbari-1500', 'city-civitates-1572'],
    images: [
      {
        src: '/images/cities-remember/nuremberg-chronicle.jpg',
        alt: 'Coloured view of walled Nuremberg in the 1493 Nuremberg Chronicle',
        credit: 'Bavarian State Library via Library of Congress World Digital Library',
        license: 'Public domain; free to use and reuse',
      },
    ],
    tags: ['Nuremberg', 'city view', 'incunable', 'wall', 'civic portrait'],
  },
  {
    id: 'city-bufalini-1551',
    room: 'city',
    secondaryRooms: ['map', 'archive'],
    title: 'Pianta di Roma',
    year: 1551,
    essaySlug: 'cities-remember',
    region: 'Rome',
    coords: [12.4964, 41.9028],
    blurb:
      'Bufalini’s large printed plan joins ancient enclosure, papal Rome and surveyed urban fabric on a continuous surface.',
    cartographer: 'Leonardo Bufalini',
    cartographerId: 'leonardo-bufalini',
    medium: 'Woodcut plan on multiple sheets',
    provenance: 'Institutional witnesses including the Accademia delle Scienze di Torino',
    bibliography: ['stanford-forma-urbis', 'tice-steiner-nolli'],
    relatedMapIds: ['city-forma-urbis', 'city-nolli-1748'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Mappa%20di%20Roma%2C%201551%20-%20Archivio%20Accademia%20delle%20Scienze%20Torino%2C%20Millon%2066%2028%20328.jpg?width=1600',
        alt: 'Leonardo Bufalini’s 1551 printed plan of Rome',
        credit: 'Accademia delle Scienze di Torino via Wikimedia Commons',
        license: 'Public Domain Mark',
      },
    ],
    tags: ['Rome', 'survey', 'woodcut', 'wall', 'urban plan'],
  },
  {
    id: 'city-agas-london',
    room: 'city',
    secondaryRooms: ['archive', 'theatre'],
    title: 'Civitas Londinum (the Agas map)',
    year: 1561,
    essaySlug: 'cities-remember',
    region: 'London',
    coords: [-0.093, 51.511],
    blurb:
      'A bird’s-eye woodcut tradition makes early modern London searchable as streets, gates, buildings and river traffic.',
    cartographer: 'Anonymous woodcut-map tradition',
    medium: 'Woodcut-derived bird’s-eye city view',
    provenance: 'London Metropolitan Archives; scholarly edition at University of Victoria',
    bibliography: ['moeml-agas'],
    relatedMapIds: ['city-civitates-1572', 'city-turgot-paris'],
    tags: ['London', 'bird’s-eye view', 'wall', 'digital edition', 'city view'],
  },
  {
    id: 'city-civitates-1572',
    room: 'theatre',
    secondaryRooms: ['city', 'archive'],
    title: 'Civitates Orbis Terrarum',
    year: 1572,
    essaySlug: 'cities-remember',
    region: 'Cologne and a world of cities',
    coords: [6.9603, 50.9375],
    blurb:
      'Braun and Hogenberg’s six-volume atlas makes hundreds of urban plans and prospects available as a repeatable comparative genre.',
    cartographer: 'Georg Braun, Frans Hogenberg and collaborators',
    cartographerId: 'georg-braun',
    engraver: 'Frans Hogenberg and collaborators',
    medium: 'Engraved and printed city atlas; many copies hand-coloured',
    provenance: 'Library of Congress, Geography and Map Division',
    bibliography: ['loc-civitates'],
    relatedMapIds: ['city-schedel-nuremberg', 'trade-barbari-1500', 'city-agas-london'],
    tags: ['city atlas', 'prospect', 'comparison', 'print', 'urban identity'],
  },
  {
    id: 'city-turgot-paris',
    room: 'theatre',
    secondaryRooms: ['city', 'map'],
    title: 'Plan de Turgot',
    year: 1739,
    essaySlug: 'cities-remember',
    region: 'Paris',
    coords: [2.3522, 48.8566],
    blurb:
      'Twenty sectional plates assemble an oblique, building-by-building performance of eighteenth-century Paris.',
    cartographer: 'Louis Bretez',
    cartographerId: 'louis-bretez',
    engraver: 'Claude Lucas',
    publisher: 'Michel-Étienne Turgot, prévôt des marchands',
    edition: 'Plan de Paris, 1739',
    medium: 'Copper engraving in twenty plates plus key map',
    bibliography: ['boutier-2007'],
    relatedMapIds: ['city-agas-london', 'city-nolli-1748'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Turgot%20map%20of%20Paris%20-%20Normale%20meridionale.jpg?width=1600',
        alt: 'Sectional plate from the oblique Turgot plan of Paris',
        credit: 'Public-domain institutional reproduction via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['Paris', 'perspective plan', 'building', 'urban spectacle', 'engraving'],
  },
  {
    id: 'city-nolli-1748',
    room: 'city',
    secondaryRooms: ['map', 'archive'],
    roomAnchor: true,
    title: 'Nuova Pianta di Roma',
    year: 1748,
    essaySlug: 'cities-remember',
    region: 'Rome',
    coords: [12.4828, 41.8933],
    blurb:
      'Nolli’s ichnographic plan joins streets and accessible interiors in a white field whose public-private grammar remains inspectable.',
    cartographer: 'Giambattista Nolli and collaborators',
    cartographerId: 'giambattista-nolli',
    scale: 'Approximately 1:2,900',
    medium: 'Copper engraving on twelve sheets',
    provenance: 'Public-domain institutional witnesses',
    bibliography: ['tice-steiner-nolli'],
    relatedMapIds: ['city-forma-urbis', 'city-bufalini-1551', 'city-turgot-paris'],
    images: [
      {
        src: '/images/cities-remember/nolli-sheet-01.jpg',
        alt: 'One engraved sheet of Giambattista Nolli’s 1748 plan of Rome',
        credit: 'Public-domain reproduction via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['Rome', 'survey', 'figure-ground', 'public interior', 'georeferencing'],
  },
  {
    id: 'city-sanborn-buffalo',
    room: 'archive',
    secondaryRooms: ['city', 'map'],
    title: 'Sanborn fire insurance map of Buffalo, volume 1',
    year: 1899,
    essaySlug: 'cities-remember',
    region: 'Buffalo',
    coords: [-78.8784, 42.8864],
    blurb:
      'A 110-sheet insurance volume remembers blocks as materials, uses and hazards selected for commercial risk assessment.',
    cartographer: 'Sanborn Map Company',
    publisher: 'Sanborn–Perris Map Company',
    edition: 'Buffalo, New York, volume 1, 1899',
    medium: 'Colour lithographed fire-insurance atlas',
    provenance: 'Library of Congress, Geography and Map Division',
    bibliography: ['loc-sanborn-guide'],
    relatedMapIds: ['city-agas-london', 'city-nolli-1748'],
    tags: ['Buffalo', 'fire insurance', 'risk', 'block', 'revision'],
  },
  {
    id: 'age-ort1-1570',
    room: 'archive',
    secondaryRooms: ['map', 'theatre'],
    title: 'Typus Orbis Terrarum, plate 1, state 1.1',
    year: 1570,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'The first documented state of Ortelius’s opening world map, before wear and repair accumulated on its copperplate.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    engraver: 'Frans Hogenberg',
    edition: 'Theatrum Orbis Terrarum, 1570 Latin edition',
    state: 'Ort 1, state 1.1',
    medium: 'Copper engraving; surviving impressions may be hand-coloured',
    bibliography: ['vandenbroecke-ort1', 'loc-ortelius', 'nuti-2003'],
    relatedMapIds: ['age-ort1-1571', 'age-ort1-1579', 'age-ort2-1587'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/OrteliusWorldMap.jpeg?width=1600',
        alt: 'Ortelius Typus Orbis Terrarum world map from the first plate',
        credit: 'Library of Congress and public-domain repositories via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['plate state', 'world map', 'atlas', 'copper engraving'],
  },
  {
    id: 'age-ort1-1571',
    room: 'archive',
    secondaryRooms: ['map'],
    title: 'Typus Orbis Terrarum, plate 1, early impression',
    year: 1571,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'A high-resolution early impression provides a second witness to the plate before its documented corner repair.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    engraver: 'Frans Hogenberg',
    state: 'Ort 1, early state',
    medium: 'Copper engraving',
    bibliography: ['vandenbroecke-ort1'],
    relatedMapIds: ['age-ort1-1570', 'age-ort1-1572'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Typus%20orbis%20terrarum%20-%20Franciscus%20Hogenbergus%2C%20sculpsit%20-%20btv1b8446648x.jpg?width=1600',
        alt: 'Early Typus Orbis Terrarum impression engraved by Frans Hogenberg',
        credit: 'Bibliothèque nationale de France via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['plate state', 'world map', 'atlas', 'copper engraving'],
  },
  {
    id: 'age-ort1-1572',
    room: 'archive',
    secondaryRooms: ['map'],
    title: 'Typus Orbis Terrarum, plate 1, 1572 impression',
    year: 1572,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'A 1572 impression keeps the early plate visible across the atlas’s rapid first sequence of language editions.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    engraver: 'Frans Hogenberg',
    state: 'Ort 1, early state',
    medium: 'Copper engraving',
    bibliography: ['vandenbroecke-ort1', 'loc-ortelius'],
    relatedMapIds: ['age-ort1-1571', 'age-ort1-1575'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/1572%20Typus%20Orbis%20Terrarum%20Ortelius.jpg?width=1600',
        alt: 'Typus Orbis Terrarum world map in a 1572 impression',
        credit: 'Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['plate state', 'world map', 'atlas', 'copper engraving'],
  },
  {
    id: 'age-ort1-1575',
    room: 'archive',
    secondaryRooms: ['map'],
    title: 'Typus Orbis Terrarum, plate 1, state 1.3',
    year: 1575,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'Bolt impressions at the lower-left corner record an attempt to stabilise a crack in the working plate.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    engraver: 'Frans Hogenberg',
    state: 'Ort 1, state 1.3',
    medium: 'Copper engraving',
    condition: 'Plate repair documented by lower-left bolt impressions',
    bibliography: ['vandenbroecke-ort1'],
    relatedMapIds: ['age-ort1-1572', 'age-ort1-1579'],
    tags: ['plate state', 'repair', 'wear', 'copper engraving'],
  },
  {
    id: 'age-ort1-1579',
    room: 'archive',
    secondaryRooms: ['map', 'theatre'],
    roomAnchor: true,
    title: 'Typus Orbis Terrarum, plate 1, state 1.4',
    year: 1579,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'The repaired crack and reworked clouds make this high-resolution impression the essay’s witness to managed age.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    engraver: 'Frans Hogenberg',
    edition: 'Theatrum Orbis Terrarum, 1579',
    state: 'Ort 1, state 1.4',
    medium: 'Copper engraving, hand-coloured',
    condition: 'Crack partly mended; cloud linework reworked',
    bibliography: ['vandenbroecke-ort1', 'nuti-2003'],
    relatedMapIds: ['age-ort1-1575', 'age-ort1-1584', 'age-ort2-1587'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ortelius%20verdenskart%201579%20(12085012186).jpg?width=1600',
        alt: 'Hand-coloured Ortelius world map printed in 1579',
        credit: 'National Library of Norway via Flickr Commons and Wikimedia Commons',
        license: 'No known copyright restrictions',
      },
    ],
    tags: ['plate state', 'repair', 'wear', 'world map'],
  },
  {
    id: 'age-ort1-1584',
    room: 'archive',
    secondaryRooms: ['map'],
    title: 'Typus Orbis Terrarum, plate 1, state 1.5',
    year: 1584,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'A newly added date coexists with progressively fading hachuring near the end of the first plate’s working life.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    engraver: 'Frans Hogenberg',
    state: 'Ort 1, state 1.5',
    medium: 'Copper engraving',
    condition: 'Date added beside the engraver’s signature; hachuring worn',
    bibliography: ['vandenbroecke-ort1'],
    relatedMapIds: ['age-ort1-1579', 'age-ort2-1587'],
    tags: ['plate state', 'wear', 'date', 'world map'],
  },
  {
    id: 'age-ort2-1587',
    room: 'archive',
    secondaryRooms: ['map', 'theatre'],
    title: 'Typus Orbis Terrarum, plate 2, state 2.1',
    year: 1587,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'The short-lived second plate renews the familiar composition while preserving corner clouds and an initial 1586 date.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    state: 'Ort 2, state 2.1',
    medium: 'Copper engraving, hand-coloured',
    bibliography: ['vandenbroecke-ort2', 'nuti-2003'],
    relatedMapIds: ['age-ort1-1584', 'age-ort2-1588', 'age-ort3-1613'],
    images: [
      {
        src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Typus%20Orbis%20Terrarum.jpg?width=1600',
        alt: 'Replacement-plate Typus Orbis Terrarum reproduction catalogued as 1587',
        credit: 'Fundação Biblioteca Nacional, Brazil, via Wikimedia Commons',
        license: 'Public domain',
      },
    ],
    tags: ['plate state', 'replacement plate', 'world map', 'atlas'],
  },
  {
    id: 'age-ort2-1588',
    room: 'archive',
    secondaryRooms: ['map'],
    title: 'Typus Orbis Terrarum, plate 2, state 2.3',
    year: 1588,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'A recut South American coastline makes geographic revision visible inside the renewed but familiar plate.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
    state: 'Ort 2, state 2.3',
    medium: 'Copper engraving',
    bibliography: ['vandenbroecke-ort2'],
    relatedMapIds: ['age-ort2-1587', 'age-ort3-1613'],
    tags: ['plate state', 'coastline revision', 'world map', 'atlas'],
  },
  {
    id: 'age-ort3-1613',
    room: 'archive',
    secondaryRooms: ['map', 'theatre'],
    title: 'Typus Orbis Terrarum, plate 3, state 3.2',
    year: 1613,
    essaySlug: 'maps-that-age',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb:
      'A posthumous state adds Le Maire Strait and removes the old date while retaining the Ortelian world-map identity.',
    cartographer: 'Abraham Ortelius workshop and successors',
    cartographerId: 'ortelius',
    state: 'Ort 3, state 3.2',
    medium: 'Copper engraving',
    bibliography: ['vandenbroecke-ort3', 'vandenbroecke-1996'],
    relatedMapIds: ['age-ort2-1587', 'age-ort2-1588'],
    tags: ['plate state', 'posthumous revision', 'world map', 'atlas'],
  },

  // Speculum Chartarum
  {
    id: 'ptolemy',
    room: 'theatre',
    secondaryRooms: ['map'],
    coveragePath: '/geo/coverage.geojson#ptolemy',
    title: 'Ptolemy Geographia',
    year: 150,
    essaySlug: 'speculum',
    region: 'Alexandria',
    coords: [29.92, 31.2],
    blurb: 'Coordinates for 8,000 places - cartography as a table of numbers.',
  },
  {
    id: 'waldseemuller',
    room: 'theatre',
    secondaryRooms: ['map'],
    coveragePath: '/geo/coverage.geojson#waldseemuller',
    title: 'Waldseemüller World Map',
    year: 1507,
    essaySlug: 'speculum',
    region: 'Saint-Dié',
    coords: [6.94, 48.28],
    blurb: 'The map that first wrote "America".',
    cartographer: 'Martin Waldseemüller',
    cartographerId: 'waldseemuller',
  },
  {
    id: 'ortelius',
    room: 'theatre',
    secondaryRooms: ['map'],
    coveragePath: '/geo/coverage.geojson#ortelius',
    title: 'Ortelius Theatrum',
    year: 1570,
    essaySlug: 'speculum',
    region: 'Antwerp',
    coords: [4.4, 51.22],
    blurb: 'The first modern atlas - the world bound as a book.',
    cartographer: 'Abraham Ortelius',
    cartographerId: 'ortelius',
  },

  // Terra Sigillata (Dacia)
  {
    id: 'peutinger',
    room: 'border',
    secondaryRooms: ['road'],
    coveragePath: '/geo/coverage.geojson#peutinger',
    title: 'Tabula Peutingeriana',
    year: 400,
    essaySlug: 'dacia',
    region: 'Roman Empire',
    coords: [12.49, 41.9],
    blurb: 'The road as the unit of space - Dacia stretched along an itinerary.',
  },
  {
    id: 'honterus',
    room: 'border',
    coveragePath: '/geo/coverage.geojson#honterus',
    title: "Honterus' Transylvania",
    year: 1532,
    essaySlug: 'dacia',
    region: 'Transylvania',
    coords: [25.6, 45.65],
    blurb: 'A humanist maps his own Carpathian homeland.',
    cartographer: 'Johannes Honterus',
    cartographerId: 'honterus',
  },
  {
    id: 'hse-rudimentum-lubeck',
    room: 'archive',
    secondaryRooms: ['road', 'theatre'],
    title: 'Rudimentum Novitiorum world map, Lübeck copy witness',
    year: 1475,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Lübeck',
    coords: [10.6866, 53.8655],
    blurb:
      'A world map printed in Lübeck names northern regions but does not draw the commercial institution around its press.',
    cartographer: 'Unknown; printed by Lucas Brandis',
    publisher: 'Lucas Brandis',
    edition: 'Rudimentum Novitiorum, ff. 85v–86r, 5 August 1475',
    medium: 'Double-page woodcut in a printed book',
    provenance: 'Bayerische Staatsbibliothek, München, bsb00031549',
    objectType: 'printed_book',
    repository: 'Bayerische Staatsbibliothek, München',
    repositoryId: 'bsb00031549',
    sourceUrl: 'https://www.digitale-sammlungen.de/en/view/bsb00031549',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'München, Bayerische Staatsbibliothek',
    publicationStatus: 'published_witness',
    bibliography: [
      {
        citation:
          'Bayerische Staatsbibliothek. Rudimentum Novitiorum. Lübeck: Lucas Brandis, 1475, ff. 85v–86r. BSB bsb00031549.',
        url: 'https://www.digitale-sammlungen.de/en/view/bsb00031549',
        year: 1475,
        title: 'Rudimentum Novitiorum',
      },
      'wubs-mrozewicz-2013-hanse',
    ],
    relatedMapIds: ['religion-rudimentum', 'hse-carta-marina'],
    relatedEssaySlugs: ['invisible-maps-religion'],
    tags: ['Hanseatic', 'Lübeck', 'incunable', 'world map', 'absence'],
  },
  {
    id: 'hse-carta-marina',
    room: 'road',
    secondaryRooms: ['map', 'theatre'],
    title: 'Carta Marina et descriptio septemtrionalium terrarum',
    year: 1539,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Northern Europe',
    coords: [18.0686, 59.3293],
    blurb:
      'Olaus Magnus makes the northern seas dense with places, creatures and movement as Hanseatic institutions enter a later phase.',
    cartographer: 'Olaus Magnus',
    publisher: 'Olaus Magnus, Venice',
    dimensions: 'Image area 125 × 170 cm',
    medium: 'Printed map',
    provenance: 'Uppsala University Library, Alvin record 88495',
    objectType: 'printed_map',
    repository: 'Uppsala University Library',
    repositoryId: 'alvin-record:88495',
    sourceUrl: 'https://www.alvin-portal.org/alvin/view.jsf?pid=alvin-record:88495',
    rightsStatement: 'Public Domain Mark; no known copyright',
    attribution: 'Uppsala University Library',
    publicationStatus: 'published_witness',
    bibliography: [
      {
        citation:
          'Uppsala University Library. Olaus Magnus, Carta Marina et descriptio septemtrionalium terrarum. Venice, 1539. Alvin record 88495.',
        url: 'https://www.alvin-portal.org/alvin/view.jsf?pid=alvin-record:88495',
        author: 'Magnus, Olaus',
        year: 1539,
      },
    ],
    relatedMapIds: ['hse-rudimentum-lubeck'],
    relatedEssaySlugs: ['invisible-maps-trade'],
    tags: ['Hanseatic', 'Baltic', 'North Sea', 'printed map', 'northern Europe'],
  },
  {
    id: 'hse-lubeck-view',
    room: 'city',
    secondaryRooms: ['road', 'archive'],
    title: 'Lübeck, from Civitates Orbis Terrarum, volume I',
    year: 1593,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Lübeck',
    coords: [10.6866, 53.8655],
    blurb:
      'The engraved city portrait calls Lübeck head of the Wendish cities and the Hanseatic society while presenting an autonomous imperial city.',
    cartographer: 'Georg Braun and Frans Hogenberg',
    edition: 'Civitates Orbis Terrarum, vol. I, p. 24a',
    medium: 'Engraved city view',
    provenance: 'Universitätsbibliothek Heidelberg, braun1593bd1, canvas 0074',
    objectType: 'city_view',
    repository: 'Universitätsbibliothek Heidelberg',
    repositoryId: 'braun1593bd1 p. 24a (canvas 0074)',
    sourceUrl: 'https://digi.ub.uni-heidelberg.de/diglit/braun1593bd1/0074',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'Universitätsbibliothek Heidelberg',
    publicationStatus: 'published_witness',
    bibliography: ['loc-civitates', 'wubs-mrozewicz-2013-hanse'],
    relatedMapIds: ['hse-hamburg-view', 'hse-london-view', 'hse-bruges-view'],
    relatedEssaySlugs: ['cities-remember'],
    tags: ['Hanseatic', 'Lübeck', 'city view', 'Civitates Orbis Terrarum'],
  },
  {
    id: 'hse-hamburg-view',
    room: 'city',
    secondaryRooms: ['road'],
    title: 'Hamburg, from Civitates Orbis Terrarum, volume I',
    year: 1593,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Hamburg',
    coords: [9.9937, 53.5511],
    blurb:
      'A river city is made visible as a civic body while the commercial relationships extending beyond it remain implicit.',
    cartographer: 'Georg Braun and Frans Hogenberg',
    edition: 'Civitates Orbis Terrarum, vol. I, p. 24a; view dated 1572',
    medium: 'Engraved city view',
    provenance: 'Universitätsbibliothek Heidelberg, braun1593bd1, canvas 0074',
    objectType: 'city_view',
    repository: 'Universitätsbibliothek Heidelberg',
    repositoryId: 'braun1593bd1 p. 24a (canvas 0074)',
    sourceUrl: 'https://digi.ub.uni-heidelberg.de/diglit/braun1593bd1/0074',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'Universitätsbibliothek Heidelberg',
    publicationStatus: 'published_witness',
    bibliography: ['loc-civitates'],
    relatedMapIds: ['hse-lubeck-view', 'hse-bremen-view'],
    relatedEssaySlugs: ['cities-remember'],
    tags: ['Hanseatic', 'Hamburg', 'city view', 'river port'],
  },
  {
    id: 'hse-london-view',
    room: 'city',
    secondaryRooms: ['road', 'archive'],
    title: 'London and the Stilliards, from Civitates Orbis Terrarum',
    year: 1593,
    essaySlug: 'the-league-that-left-no-map',
    region: 'London',
    coords: [-0.1278, 51.5074],
    blurb:
      'The London plate pairs an urban view with a text naming the Steelyard, four Kontore and a confederated society of cities.',
    cartographer: 'Georg Braun and Frans Hogenberg',
    edition: 'Civitates Orbis Terrarum, vol. I, p. Aa',
    medium: 'Engraved city view with descriptive text',
    provenance: 'Universitätsbibliothek Heidelberg, braun1593bd1, canvas 0026',
    objectType: 'city_view',
    repository: 'Universitätsbibliothek Heidelberg',
    repositoryId: 'braun1593bd1 p. Aa (canvas 0026)',
    sourceUrl: 'https://digi.ub.uni-heidelberg.de/diglit/braun1593bd1/0026',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'Universitätsbibliothek Heidelberg',
    publicationStatus: 'published_witness',
    bibliography: ['loc-civitates', 'unesco-hanse-documents-2017'],
    relatedMapIds: ['hse-lubeck-view', 'hse-bruges-view', 'city-agas-london'],
    relatedEssaySlugs: ['cities-remember'],
    tags: ['Hanseatic', 'London', 'Steelyard', 'Kontor', 'city view'],
  },
  {
    id: 'hse-bruges-view',
    room: 'city',
    secondaryRooms: ['road', 'archive'],
    title: 'Bruges, from Civitates Orbis Terrarum, volume I',
    year: 1593,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Bruges',
    coords: [3.2247, 51.2093],
    blurb:
      'A circular city portrait describes Bruges as having once been a flourishing emporium without fixing a single date for decline.',
    cartographer: 'Georg Braun and Frans Hogenberg',
    edition: 'Civitates Orbis Terrarum, vol. I, p. 16a',
    medium: 'Engraved bird’s-eye city plan',
    provenance: 'Universitätsbibliothek Heidelberg, braun1593bd1, canvas 0058',
    objectType: 'city_view',
    repository: 'Universitätsbibliothek Heidelberg',
    repositoryId: 'braun1593bd1 p. 16a (canvas 0058)',
    sourceUrl: 'https://digi.ub.uni-heidelberg.de/diglit/braun1593bd1/0058',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'Universitätsbibliothek Heidelberg',
    publicationStatus: 'published_witness',
    bibliography: ['loc-civitates', 'unesco-hanse-documents-2017'],
    relatedMapIds: ['hse-london-view', 'hse-lubeck-view'],
    relatedEssaySlugs: ['cities-remember'],
    tags: ['Hanseatic', 'Bruges', 'Kontor', 'city view', 'emporium'],
  },
  {
    id: 'hse-cologne-view',
    room: 'city',
    secondaryRooms: ['road', 'archive'],
    title: 'Cologne, from Civitates Orbis Terrarum, volume I',
    year: 1593,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Cologne',
    coords: [6.9603, 50.9375],
    blurb:
      'The Rhine city’s plate names a league of seventy-two cities and four principal cities, a claim kept distinct from the four Kontore.',
    cartographer: 'Georg Braun and Frans Hogenberg',
    edition: 'Civitates Orbis Terrarum, vol. I, p. 38a',
    medium: 'Engraved bird’s-eye city plan',
    provenance: 'Universitätsbibliothek Heidelberg, braun1593bd1, canvas 0103',
    objectType: 'city_view',
    repository: 'Universitätsbibliothek Heidelberg',
    repositoryId: 'braun1593bd1 p. 38a (canvas 0103)',
    sourceUrl: 'https://digi.ub.uni-heidelberg.de/diglit/braun1593bd1/0103',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'Universitätsbibliothek Heidelberg',
    publicationStatus: 'published_witness',
    bibliography: ['loc-civitates'],
    relatedMapIds: ['hse-london-view', 'hse-bremen-view'],
    relatedEssaySlugs: ['cities-remember'],
    tags: ['Hanseatic', 'Cologne', 'city view', 'Rhine'],
  },
  {
    id: 'hse-bremen-view',
    room: 'city',
    secondaryRooms: ['road'],
    title: 'Bremen, from the four-city Civitates plate',
    year: 1593,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Bremen',
    coords: [8.8017, 53.0793],
    blurb:
      'Bremen appears as a river prospect on a sheet whose Lüneburg panel also names the salt economy behind a major corridor.',
    cartographer: 'Georg Braun and Frans Hogenberg',
    edition: 'Civitates Orbis Terrarum, vol. I, p. 23a',
    medium: 'Engraved four-city plate',
    provenance: 'Universitätsbibliothek Heidelberg, braun1593bd1, canvas 0072',
    objectType: 'city_view',
    repository: 'Universitätsbibliothek Heidelberg',
    repositoryId: 'braun1593bd1 p. 23a (canvas 0072)',
    sourceUrl: 'https://digi.ub.uni-heidelberg.de/diglit/braun1593bd1/0072',
    rightsStatement: 'Public Domain Mark 1.0',
    attribution: 'Universitätsbibliothek Heidelberg',
    publicationStatus: 'published_witness',
    bibliography: ['loc-civitates'],
    relatedMapIds: ['hse-hamburg-view', 'hse-cologne-view'],
    relatedEssaySlugs: ['cities-remember'],
    tags: ['Hanseatic', 'Bremen', 'Lüneburg', 'salt', 'city view'],
  },
  {
    id: 'hse-novgorod-schra',
    room: 'archive',
    secondaryRooms: ['road', 'city'],
    title: 'Second Novgorod Schra, Riga copy',
    year: 1295,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Novgorod / Riga',
    coords: [31.2742, 58.5215],
    blurb:
      'A sixty-four-article rule text makes Peterhof’s internal discipline visible without turning the merchant compound into territory.',
    edition: 'Riga copy dated before 1298; selected documentary phase AD 1295',
    medium: 'Manuscript ordinance',
    provenance: 'Latvian State Historical Archives, Fonds 673, Directory 4, Box 18, no. 7',
    objectType: 'documentary',
    repository: 'Latvian State Historical Archives',
    repositoryId: 'Fonds 673, Directory 4, Box 18, no. 7',
    sourceUrl:
      'https://www.hansemuseum.eu/records/die-zweite-nowgoroder-schra-kontorordnung-von-1295/',
    rightsStatement: 'Archive image in copyright; metadata and evidence published without image',
    attribution: 'Latvian State Historical Archives',
    publicationStatus: 'reference_only',
    bibliography: ['unesco-hanse-documents-2017'],
    relatedMapIds: ['hse-rudimentum-lubeck'],
    tags: ['Hanseatic', 'Novgorod', 'Peterhof', 'ordinance', 'reference only'],
  },
  {
    id: 'hse-bergen-court-books',
    room: 'archive',
    secondaryRooms: ['city', 'road'],
    title: 'Bergen Kontor court books, 1633–1759',
    year: 1633,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Bergen',
    coords: [5.3221, 60.39299],
    blurb:
      'Nine court books record internal jurisdiction, fees, fire safety, office holders and price lists across Bryggen’s long afterlife.',
    medium: 'Manuscript court books',
    provenance: 'Archive of the Hanseatic City of Lübeck, 5.1-1.4 Bergenfahrer, 1039–1047',
    objectType: 'documentary',
    repository: 'Archive of the Hanseatic City of Lübeck',
    repositoryId: '5.1-1.4 Bergenfahrer, 1039–1047',
    sourceUrl:
      'https://media.unesco.org/sites/default/files/webform/mow001/documents-on-the-history-of-the-hanse_nom_en_0.pdf',
    rightsStatement: 'Archive material in copyright; metadata and evidence published without image',
    attribution: 'Archive of the Hanseatic City of Lübeck',
    publicationStatus: 'reference_only',
    bibliography: ['unesco-hanse-documents-2017', 'unesco-bryggen'],
    relatedMapIds: ['hse-carta-marina'],
    tags: ['Hanseatic', 'Bergen', 'Bryggen', 'court books', 'reference only'],
  },
  {
    id: 'hse-london-ordinance',
    room: 'archive',
    secondaryRooms: ['city', 'road'],
    title: 'London Kontor by-laws, 1554',
    year: 1554,
    essaySlug: 'the-league-that-left-no-map',
    region: 'London',
    coords: [-0.1278, 51.5074],
    blurb:
      'Thirty leaves regulate elections, jurisdiction, finance, conduct and training inside the Steelyard community.',
    medium: 'Manuscript ordinance',
    provenance: 'Archive of the Hanseatic City of Lübeck, 1.1-3.2 ASA Externa Anglicana, 728',
    objectType: 'documentary',
    repository: 'Archive of the Hanseatic City of Lübeck',
    repositoryId: '1.1-3.2 ASA Externa Anglicana, 728',
    sourceUrl:
      'https://media.unesco.org/sites/default/files/webform/mow001/documents-on-the-history-of-the-hanse_nom_en_0.pdf',
    rightsStatement: 'Archive material in copyright; metadata and evidence published without image',
    attribution: 'Archive of the Hanseatic City of Lübeck',
    publicationStatus: 'reference_only',
    bibliography: ['unesco-hanse-documents-2017'],
    relatedMapIds: ['hse-london-view'],
    tags: ['Hanseatic', 'London', 'Steelyard', 'by-laws', 'reference only'],
  },
  {
    id: 'hse-bruges-charters',
    room: 'archive',
    secondaryRooms: ['city', 'road'],
    title: 'Bruges privilege charters, 1458–1502',
    year: 1458,
    essaySlug: 'the-league-that-left-no-map',
    region: 'Bruges',
    coords: [3.2247, 51.2093],
    blurb:
      'A charter group records building, staple and excise privileges as negotiated access inside a host city.',
    medium: 'Privilege charters',
    provenance:
      'City Archives of Bruges, Political charters, 1st series 1016, 1160, 1434; 2nd series 1617',
    objectType: 'charter',
    repository: 'City Archives of Bruges',
    repositoryId: 'Political charters, 1st series 1016, 1160, 1434; 2nd series 1617',
    sourceUrl:
      'https://media.unesco.org/sites/default/files/webform/mow001/documents-on-the-history-of-the-hanse_nom_en_0.pdf',
    rightsStatement: 'Public-domain objects; direct repository surrogate not yet secured',
    attribution: 'City Archives of Bruges',
    publicationStatus: 'reference_only',
    bibliography: ['unesco-hanse-documents-2017'],
    relatedMapIds: ['hse-bruges-view'],
    tags: ['Hanseatic', 'Bruges', 'privilege', 'charter', 'reference only'],
  },
  {
    id: 'specht',
    room: 'border',
    coveragePath: '/geo/coverage.geojson#specht',
    title: 'Specht Map of Dacia',
    year: 1791,
    essaySlug: 'dacia',
    region: 'Romania',
    coords: [26.1, 44.43],
    blurb: 'Habsburg military survey turns territory into administered grid.',
  },
];

// Validated at module load so a malformed record fails the build, not the browser.
export const CORPUS: HistoricalMap[] = RAW.map((m) => HistoricalMapSchema.parse(m));

export function getCorpus(): HistoricalMap[] {
  return [...CORPUS].sort((a, b) => a.year - b.year);
}

/**
 * Atlas-critical projection (ATLAS-802 / KAN-66). AtlasMap consumes *this* so
 * rich catalogue fields never enter the inline client payload. Sorted like
 * getCorpus for a stable pin/list order.
 */
export function getCorpusCore(): MapCore[] {
  return getCorpus().map((m) => MapCoreSchema.parse(m));
}

export function getMapById(id: string): HistoricalMap | undefined {
  return CORPUS.find((m) => m.id === id);
}

export function corpusYearRange(): [number, number] {
  const years = CORPUS.map((m) => m.year);
  return [Math.min(...years), Math.max(...years)];
}

/**
 * Human century label for a signed year (negative = BC), used as a catalogue
 * facet. 600 BC → "6th century BC"; AD 150 → "2nd century"; 1569 → "16th century".
 */
export function centuryLabel(year: number): string {
  const n = Math.ceil(Math.abs(year) / 100);
  const suffix =
    n % 100 >= 11 && n % 100 <= 13
      ? 'th'
      : n % 10 === 1
        ? 'st'
        : n % 10 === 2
          ? 'nd'
          : n % 10 === 3
            ? 'rd'
            : 'th';
  return `${n}${suffix} century${year < 0 ? ' BC' : ''}`;
}
